### ISSUE TITLE
Picture rotation

### ISSUE THREAD

**Issue by ghost** [dc74089/oneshirt#1]
When pictures are uploaded there is no option to rotate them in any direction

**Comment by dc74089** [comment]
The site seems to be auto-rotating some images the wrong way on upload, so a manual correction button is a definite need.

**Comment by dc74089** [comment]
This is mostly fixed by 2f42717964c99030cd4a8ba46d51d1548286c7b2 which respects EXIF data when a photo is uploaded, but there is still no way to manually rotate. Closing for now, but may revisit later.
