### ISSUE TITLE
Error when adding an item

### ISSUE THREAD

**Issue by theforkofyork** [dc74089/oneshirt#4]
when adding a shirt I get a server error

**Comment by dc74089** [comment]
Thanks! I will look into this, but without more information it will be hard to diagnose. Can you explain the circumstances, files, and inputs that lead to the error?

**Comment by Negative4** [comment]
Woah

**Comment by dc74089** [comment]
Closing as Not Enough Info/Not Reproducible. Various bugfixes will probably (or may already have) account for this.
